import { Incident } from "./types";

export const SAMPLE_INCIDENTS: Incident[] = [
  // ==================== IRANIAN STRIKES ====================

  // --- UAE — DUBAI ---
  { id: "ir-dubai-1", date: "2026-02-28", location: "Dubai, UAE", lat: 25.276, lng: 55.296, description: "Iranian ballistic missile direct impact in Dubai", details: "An Iranian ballistic missile scored a confirmed direct impact in Dubai. Fire was observed at the impact site. Scenes from the impact were documented by multiple OSINT channels.", weapon: "Ballistic missile", target_type: "Urban area", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: false },
  { id: "ir-dubai-2", date: "2026-02-28", location: "Palm Jumeirah, Dubai", lat: 25.1104, lng: 55.1406, description: "Missile debris fire at Palm Jumeirah", details: "Fire burning at Palm Jumeirah caused by a downed Iranian ballistic missile. Coordinates confirmed at 25.110391, 55.140636.", weapon: "Ballistic missile", target_type: "Residential / luxury area", video_url: "", source_url: "https://t.me/AMK_Mapping", source: "telegram", side: "iran", target_military: false },
  { id: "ir-dubai-3", date: "2026-02-28", location: "Burj Khalifa area, Dubai", lat: 25.1972, lng: 55.2744, description: "Shahed-136 drone impacts near Burj Khalifa", details: "An Iranian Shahed-136 drone impacted right next to the Burj Khalifa, the world's tallest building. Multiple additional drone impacts reported in the area.", weapon: "Shahed-136 drone", target_type: "Urban landmark", video_url: "", source_url: "https://t.me/AMK_Mapping", source: "telegram", side: "iran", target_military: false },
  { id: "ir-dubai-4", date: "2026-02-28", location: "Burj Al Arab, Dubai", lat: 25.1412, lng: 55.1855, description: "Shahed drone strikes Burj Al Arab — structural fire", details: "An Iranian Shahed drone struck the Burj Al Arab hotel, igniting a fiberglass structural beam across multiple floors of the 321-meter, 60-story tower.", weapon: "Shahed-136 drone", target_type: "Luxury hotel / landmark", video_url: "", source_url: "https://t.me/intelslava", source: "telegram", side: "iran", target_military: false },
  { id: "ir-dubai-5", date: "2026-02-28", location: "Dubai International Airport", lat: 25.2528, lng: 55.3644, description: "Dubai Airport repeatedly struck by Shahed drones — 4 injured", details: "Iran repeatedly hit Dubai International Airport with Shahed-131/136 drones. A concourse sustained damage, 4 staff were injured. The airport was evacuated.", weapon: "Shahed-131/136 drone", target_type: "Airport", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "iran", target_military: false },
  { id: "ir-dubai-6", date: "2026-02-28", location: "Jebel Ali Port, Dubai", lat: 25.0174, lng: 55.0578, description: "Significant damage at Jebel Ali Port", details: "Reports of significant damage to Jebel Ali Port, the largest port in the Middle East. Fires visible with impacts confirmed.", weapon: "Ballistic missile", target_type: "Port infrastructure", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: false },

  // --- UAE — ABU DHABI ---
  { id: "ir-ad-1", date: "2026-02-28", location: "Abu Dhabi, UAE", lat: 24.453, lng: 54.377, description: "Missile debris kills 1 in Abu Dhabi residential area", details: "Debris from an intercepted Iranian ballistic missile fell on a residential area in Abu Dhabi, killing one person.", weapon: "Ballistic missile", target_type: "Residential area", video_url: "", source_url: "https://t.me/AMK_Mapping", source: "telegram", side: "iran", target_military: false },
  { id: "ir-ad-2", date: "2026-02-28", location: "Zayed International Airport, Abu Dhabi", lat: 24.443, lng: 54.651, description: "Abu Dhabi airport struck — 1 dead, 7 injured", details: "Zayed International Airport struck by Iranian Shahed drones. One person killed and seven injured.", weapon: "Shahed-136 drone", target_type: "Airport", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: false },
  { id: "ir-ad-3", date: "2026-03-01", location: "Zayed Port, Abu Dhabi", lat: 24.518, lng: 54.382, description: "Iranian impact at Zayed Port confirmed", details: "Iran attacked Zayed Port in Abu Dhabi. Impact confirmed with visible damage.", weapon: "Ballistic missile", target_type: "Port infrastructure", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "iran", target_military: false },
  { id: "ir-ad-4", date: "2026-02-28", location: "Al Dhafra Air Base, Abu Dhabi", lat: 24.248, lng: 54.548, description: "US Al Dhafra Air Base struck by Iranian missiles", details: "US Al Dhafra Air Base struck by Iranian ballistic missiles. Smoke rising from base. Iran also launched drone strikes later.", weapon: "Ballistic missile", target_type: "US military base", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: true },

  // --- UAE — SHARJAH ---
  { id: "ir-sharjah-1", date: "2026-02-28", location: "Sharjah, UAE", lat: 25.346, lng: 55.421, description: "Shahed-136 drone impacts Sharjah", details: "An Iranian Shahed-136 drone struck the city of Sharjah.", weapon: "Shahed-136 drone", target_type: "Urban area", video_url: "", source_url: "https://t.me/AMK_Mapping", source: "telegram", side: "iran", target_military: false },

  // --- BAHRAIN ---
  { id: "ir-bah-1", date: "2026-02-28", location: "Manama high-rise, Bahrain", lat: 26.228, lng: 50.586, description: "Shahed drone strikes residential high-rise — building in flames", details: "An Iranian Shahed drone struck a residential high-rise in Manama. The building caught fire across multiple floors. Residents filmed from inside as drones impacted floors above.", weapon: "Shahed-136 drone", target_type: "Residential high-rise", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: false },
  { id: "ir-bah-2", date: "2026-02-28", location: "US Navy 5th Fleet HQ, Bahrain", lat: 26.237, lng: 50.609, description: "Multiple impacts on US Navy 5th Fleet base", details: "US Navy 5th Fleet HQ struck by Iranian Shahed drones and ballistic missiles. Warehouse and radar installation hit. ~300 missiles launched at Bahrain total.", weapon: "Shahed-136 drone", target_type: "US naval base", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "iran", target_military: true },
  { id: "ir-bah-3", date: "2026-02-28", location: "Crowne Plaza Hotel, Manama", lat: 26.222, lng: 50.593, description: "5-star Crowne Plaza hotel directly hit", details: "Bahrain's 5-star Crowne Plaza hotel in Manama directly hit by Iranian strike.", weapon: "Ballistic missile", target_type: "Hotel / civilian", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: false },
  { id: "ir-bah-4", date: "2026-02-28", location: "Bahrain International Airport", lat: 26.271, lng: 50.634, description: "Iranian drone strikes Bahrain airport", details: "Shahed drone struck Bahrain International Airport. Material damage, no loss of life.", weapon: "Shahed-136 drone", target_type: "Airport", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "iran", target_military: false },

  // --- QATAR ---
  { id: "ir-qatar-1", date: "2026-02-28", location: "Al-Wakrah, Qatar", lat: 25.172, lng: 51.604, description: "Ballistic missile impact at Al-Wakrah", details: "Iranian ballistic missile impacted at Al-Wakrah, south of Doha. Qatar targeted by 44 ballistic missiles and 8 drones total.", weapon: "Ballistic missile", target_type: "City", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: false },
  { id: "ir-qatar-2", date: "2026-02-28", location: "Al Udeid Air Base, Qatar", lat: 25.117, lng: 51.315, description: "Iranian missile impacts Al Udeid — Patriot fails", details: "Iranian ballistic missile impacted Al Udeid Air Base. Video showed US Patriot system failing to intercept.", weapon: "Ballistic missile", target_type: "US military base", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: true },
  { id: "ir-qatar-3", date: "2026-03-01", location: "Doha, Qatar", lat: 25.286, lng: 51.534, description: "Multiple ballistic missile impacts in Doha", details: "Multiple Iranian ballistic missile impacts confirmed in Doha. Hamad International Airport evacuated.", weapon: "Ballistic missile", target_type: "Capital city", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "iran", target_military: false },

  // --- KUWAIT ---
  { id: "ir-kuwait-1", date: "2026-02-28", location: "Ali Al Salem Air Base, Kuwait", lat: 29.347, lng: 47.521, description: "Multiple missile impacts — satellite confirms 4 fires", details: "Ali Al Salem Air Base struck by multiple Iranian ballistic missiles. Satellite imagery confirmed 4 fires. 3 Kuwait armed forces members injured.", weapon: "Ballistic missile", target_type: "US/Kuwait military base", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: true },
  { id: "ir-kuwait-2", date: "2026-02-28", location: "Kuwait International Airport", lat: 29.227, lng: 47.969, description: "Shahed drone strikes airport — fires, injuries", details: "Iranian Shahed-136 drone struck old terminal of Kuwait International Airport. Several injuries, interior fires. CCTV captured impact.", weapon: "Shahed-136 drone", target_type: "Airport", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "iran", target_military: false },

  // --- SAUDI ARABIA ---
  { id: "ir-saudi-1", date: "2026-02-28", location: "Riyadh, Saudi Arabia", lat: 24.713, lng: 46.675, description: "Explosions confirmed in Riyadh", details: "AFP confirmed explosions in Riyadh.", weapon: "Ballistic missile", target_type: "Capital city", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "iran", target_military: false },
  { id: "ir-saudi-2", date: "2026-02-28", location: "Prince Sultan Air Base, Saudi Arabia", lat: 24.062, lng: 47.581, description: "IRGC claims 'precise hit' on Prince Sultan Air Base", details: "IRGC announced Prince Sultan Air Base was 'precisely hit' by missiles and drones.", weapon: "Ballistic missile", target_type: "US/Saudi military base", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: true },

  // --- JORDAN ---
  { id: "ir-jordan-1", date: "2026-02-28", location: "Muwaffaq Salti Air Base, Jordan", lat: 32.356, lng: 36.782, description: "Iranian missile direct impact on US base", details: "Iranian ballistic missile direct impact at US Muwaffaq Salti Air Base. Footage documented.", weapon: "Ballistic missile", target_type: "US military base", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: true },
  { id: "ir-jordan-2", date: "2026-02-28", location: "Amman, Jordan", lat: 31.956, lng: 35.946, description: "Missile debris in populated areas — 54 incidents", details: "Debris from intercepted missiles fell in populated areas. 54 incidents of falling debris causing material damage.", weapon: "Ballistic missile", target_type: "Capital city (debris)", video_url: "", source_url: "https://t.me/AMK_Mapping", source: "telegram", side: "iran", target_military: false },

  // --- IRAQ ---
  { id: "ir-iraq-1", date: "2026-02-28", location: "Erbil US base / airport, Iraq", lat: 36.234, lng: 43.963, description: "Multiple drone impacts on US base in Erbil", details: "Drones attacked Erbil International Airport and US base. Shahed-107 hit US C-RAM system. US Consulate closed.", weapon: "Shahed-107 drone", target_type: "US military base / airport", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "iran", target_military: true },
  { id: "ir-iraq-2", date: "2026-02-28", location: "Harir Air Base, Iraq", lat: 36.541, lng: 44.381, description: "2 drone impacts at US-operated Harir Air Base", details: "US-operated Harir Air Base hit by 2 drones.", weapon: "Shahed drone", target_type: "US military base", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: true },

  // --- OMAN ---
  { id: "ir-oman-1", date: "2026-02-28", location: "Duqm Port, Oman", lat: 19.673, lng: 57.711, description: "Two drone impacts at Duqm port", details: "Two drones targeted Duqm Commercial Port. Visual confirmation of direct impacts.", weapon: "Shahed drone", target_type: "Commercial port", video_url: "", source_url: "https://t.me/AMK_Mapping", source: "telegram", side: "iran", target_military: false },

  // --- MARITIME ---
  { id: "ir-sea-1", date: "2026-02-28", location: "Off Musandam, Oman", lat: 26.2, lng: 56.25, description: "Tanker 'Skylight' struck — fire, sinking, 4 injured", details: "Palau-flagged tanker 'Skylight' struck 5nm off Musandam. 4 injured, on fire, began sinking.", weapon: "Anti-ship missile", target_type: "Oil tanker", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: false },
  { id: "ir-sea-2", date: "2026-02-28", location: "50nm N of Muscat", lat: 24.0, lng: 57.5, description: "Vessel struck — engine room fire", details: "UKMTO: vessel struck by projectile. Engine room fire controlled.", weapon: "Anti-ship missile", target_type: "Commercial vessel", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: false },
  { id: "ir-sea-3", date: "2026-02-28", location: "Strait of Hormuz", lat: 26.56, lng: 56.15, description: "Oil tanker struck in Strait of Hormuz", details: "Marshall Islands-flagged tanker struck. 150+ tankers halted.", weapon: "Anti-ship missile", target_type: "Oil tanker", video_url: "", source_url: "https://t.me/AMK_Mapping", source: "telegram", side: "iran", target_military: false },

  // --- BAHRAIN (EXPANDED — ~300 missiles reported) ---
  { id: "ir-bah-5", date: "2026-02-28", location: "Isa Air Base, Bahrain", lat: 25.918, lng: 50.591, description: "IRGC hits Isa Air Base — F-16 shelters struck", details: "Iranian ballistic missiles struck Isa Air Base, home to Bahrain's F-16 fleet and USAF detachment. Multiple hardened aircraft shelters hit. Secondary fires from fuel storage.", weapon: "Ballistic missile", target_type: "Air base (US/Bahrain)", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: true },
  { id: "ir-bah-6", date: "2026-02-28", location: "King Fahd Causeway, Bahrain", lat: 26.117, lng: 50.338, description: "Shahed drone impacts causeway — traffic halted", details: "Iranian Shahed-136 drone struck the King Fahd Causeway connecting Bahrain to Saudi Arabia. Traffic halted, structural damage to one span. Thousands stranded.", weapon: "Shahed-136 drone", target_type: "Infrastructure / bridge", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "iran", target_military: false },
  { id: "ir-bah-7", date: "2026-02-28", location: "Muharraq, Bahrain", lat: 26.257, lng: 50.612, description: "Residential area in Muharraq hit by missile debris", details: "Interceptor debris and missile fragments fell on Muharraq residential neighborhoods. 8 civilians injured, significant property damage to apartments and cars.", weapon: "Ballistic missile", target_type: "Residential (debris)", video_url: "", source_url: "https://t.me/AMK_Mapping", source: "telegram", side: "iran", target_military: false },
  { id: "ir-bah-8", date: "2026-02-28", location: "Sitra Industrial Area, Bahrain", lat: 26.148, lng: 50.620, description: "Drone strikes oil storage — fire at BAPCO refinery", details: "Iranian Shahed drone struck near BAPCO oil refinery at Sitra. Oil storage tank ignited. Fire crews battled blaze for hours.", weapon: "Shahed-136 drone", target_type: "Oil refinery / industrial", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: false },
  { id: "ir-bah-9", date: "2026-02-28", location: "Juffair, Bahrain", lat: 26.214, lng: 50.601, description: "Multiple impacts in Juffair near US facilities", details: "Multiple Shahed drone impacts in Juffair area near NSA Bahrain compound. Adjacent shopping mall and residential towers damaged. 3 US personnel treated for minor injuries.", weapon: "Shahed-136 drone", target_type: "US military area / civilian", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "iran", target_military: true },
  { id: "ir-bah-10", date: "2026-02-28", location: "Bahrain Financial Harbour, Manama", lat: 26.238, lng: 50.564, description: "Missile debris hits Financial Harbour district", details: "Falling missile debris struck buildings in Bahrain's Financial Harbour business district. Office tower windows shattered across 12 floors. Area evacuated.", weapon: "Ballistic missile", target_type: "Commercial district (debris)", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: false },

  // --- QATAR (EXPANDED — 44 ballistic + 8 drones reported) ---
  { id: "ir-qatar-4", date: "2026-02-28", location: "Hamad International Airport, Qatar", lat: 25.261, lng: 51.614, description: "Shahed drones strike airport — all flights cancelled", details: "Two Shahed-136 drones impacted Hamad International Airport. Terminal building glass facade shattered. All flights cancelled indefinitely. Thousands of passengers stranded.", weapon: "Shahed-136 drone", target_type: "Airport", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "iran", target_military: false },
  { id: "ir-qatar-5", date: "2026-02-28", location: "The Pearl-Qatar, Doha", lat: 25.366, lng: 51.552, description: "Ballistic missile impact near The Pearl — luxury island hit", details: "Iranian ballistic missile impacted 200m from The Pearl-Qatar artificial island. Shockwave damaged luxury residences and marina. Several yachts sunk at dock.", weapon: "Ballistic missile", target_type: "Luxury residential", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: false },
  { id: "ir-qatar-6", date: "2026-02-28", location: "Camp As Sayliyah, Qatar", lat: 25.203, lng: 51.353, description: "US Army pre-positioned equipment base struck", details: "Iranian missiles struck Camp As Sayliyah, a major US Army pre-positioned stock facility. Warehouses storing MRAPs and armored vehicles hit. Multiple fires.", weapon: "Ballistic missile", target_type: "US military base", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: true },
  { id: "ir-qatar-7", date: "2026-02-28", location: "Lusail City, Qatar", lat: 25.420, lng: 51.490, description: "Missile debris falls on Lusail — World Cup stadium area", details: "Missile interceptor debris fell on Lusail City, the planned city built for the 2022 World Cup. Damage to Lusail Stadium parking area and adjacent residential towers.", weapon: "Ballistic missile", target_type: "City (debris)", video_url: "", source_url: "https://t.me/AMK_Mapping", source: "telegram", side: "iran", target_military: false },
  { id: "ir-qatar-8", date: "2026-02-28", location: "Ras Laffan Industrial City, Qatar", lat: 25.917, lng: 51.565, description: "Drone strikes near world's largest LNG facility", details: "Shahed-136 drone impacted the perimeter of Ras Laffan Industrial City, home to the world's largest LNG production facilities. No direct hit on LNG infrastructure but security lockdown triggered. Global gas prices spiked.", weapon: "Shahed-136 drone", target_type: "LNG facility perimeter", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: false },
  { id: "ir-qatar-9", date: "2026-02-28", location: "Education City, Doha", lat: 25.315, lng: 51.425, description: "Ballistic missile impact near Education City campus", details: "Iranian ballistic missile struck open ground 500m from Qatar Foundation's Education City. Campus universities evacuated. Minor blast injuries to students.", weapon: "Ballistic missile", target_type: "Educational area", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "iran", target_military: false },
  { id: "ir-qatar-10", date: "2026-03-01", location: "Al Udeid perimeter, Qatar", lat: 25.130, lng: 51.330, description: "Second wave of missiles at Al Udeid — runway cratered", details: "Second wave of Iranian ballistic missiles targeted Al Udeid Air Base. Main runway cratered in 3 locations. US THAAD system intercepted 4 of 7 incoming missiles.", weapon: "Ballistic missile", target_type: "US military base", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: true },

  // --- SAUDI ARABIA (EXPANDED) ---
  { id: "ir-saudi-3", date: "2026-02-28", location: "King Abdulaziz Air Base, Dhahran", lat: 26.265, lng: 50.152, description: "Missiles strike Dhahran air base — echoes of 1991", details: "Iranian ballistic missiles struck King Abdulaziz Air Base in Dhahran, the same base targeted by Iraq in 1991. Multiple impacts on runway and hangar areas.", weapon: "Ballistic missile", target_type: "Air base (Saudi/US)", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: true },
  { id: "ir-saudi-4", date: "2026-02-28", location: "Aramco Abqaiq Facility, Saudi Arabia", lat: 25.938, lng: 49.682, description: "Shahed drones strike Abqaiq oil processing plant", details: "Iranian Shahed-136 drones struck the Saudi Aramco Abqaiq oil processing facility, the world's largest. Echoes of the 2019 Houthi attack. Multiple processing units hit. Global oil prices surged past $130/barrel.", weapon: "Shahed-136 drone", target_type: "Oil processing facility", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "iran", target_military: false },
  { id: "ir-saudi-5", date: "2026-02-28", location: "Ras Tanura Oil Terminal, Saudi Arabia", lat: 26.644, lng: 50.171, description: "Anti-ship missile hits near Ras Tanura terminal", details: "IRGC anti-ship missile struck waters near Ras Tanura, the world's largest offshore oil loading facility. One tanker at berth sustained minor damage. Loading operations suspended.", weapon: "Anti-ship missile", target_type: "Oil terminal / maritime", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: false },
  { id: "ir-saudi-6", date: "2026-02-28", location: "Dammam, Saudi Arabia", lat: 26.434, lng: 50.103, description: "Missile debris in Dammam residential areas", details: "Intercepted missile debris fell on residential areas in Dammam. 3 injured, cars and buildings damaged. Saudi air defense intercepted most incoming missiles.", weapon: "Ballistic missile", target_type: "City (debris)", video_url: "", source_url: "https://t.me/AMK_Mapping", source: "telegram", side: "iran", target_military: false },
  { id: "ir-saudi-7", date: "2026-02-28", location: "King Khalid Military City, Saudi Arabia", lat: 27.897, lng: 45.541, description: "Missiles strike KKMC — Saudi military hub hit", details: "Iranian ballistic missiles struck King Khalid Military City in northern Saudi Arabia. Vehicle maintenance facilities and communications arrays destroyed.", weapon: "Ballistic missile", target_type: "Military city / garrison", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: true },
  { id: "ir-saudi-8", date: "2026-02-28", location: "Jeddah, Saudi Arabia", lat: 21.486, lng: 39.183, description: "Long-range Khorramshahr missile reaches Jeddah", details: "Iran's Khorramshahr-4 MRBM reached Jeddah on the Red Sea coast, demonstrating Iran's 2,000km+ strike range. Impact in industrial area. No casualties reported.", weapon: "Khorramshahr-4 missile", target_type: "Industrial area", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "iran", target_military: false },

  // --- KUWAIT (EXPANDED) ---
  { id: "ir-kuwait-3", date: "2026-02-28", location: "Camp Arifjan, Kuwait", lat: 29.104, lng: 48.078, description: "US Camp Arifjan struck — major logistics hub", details: "Iranian missiles struck Camp Arifjan, the primary US Army logistical hub in Kuwait. Warehouse facilities and vehicle staging areas hit. 5 US soldiers injured.", weapon: "Ballistic missile", target_type: "US military base", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: true },
  { id: "ir-kuwait-4", date: "2026-02-28", location: "Camp Buehring, Kuwait", lat: 29.510, lng: 47.450, description: "Camp Buehring hit — troop staging base", details: "Iranian Shahed drones struck Camp Buehring, a major US troop staging and training facility in northern Kuwait. Tent city and range facilities damaged.", weapon: "Shahed-136 drone", target_type: "US military base", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "iran", target_military: true },
  { id: "ir-kuwait-5", date: "2026-02-28", location: "Kuwait City waterfront", lat: 29.372, lng: 47.979, description: "Missile debris hits Kuwait City — 2 killed", details: "Debris from an intercepted Iranian missile struck Kuwait City waterfront area near Kuwait Towers. 2 civilians killed, 11 injured. Significant damage to vehicles and storefronts.", weapon: "Ballistic missile", target_type: "City (debris)", video_url: "", source_url: "https://t.me/AMK_Mapping", source: "telegram", side: "iran", target_military: false },

  // --- UAE — ADDITIONAL ---
  { id: "ir-dubai-7", date: "2026-02-28", location: "Al Minhad Air Base, Dubai", lat: 25.025, lng: 55.371, description: "Al Minhad coalition air base struck", details: "Iranian ballistic missiles struck Al Minhad Air Base, used by Australian, Canadian, and coalition forces. Hangar and maintenance area hit. Coalition aircraft damaged on the tarmac.", weapon: "Ballistic missile", target_type: "Coalition military base", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: true },
  { id: "ir-dubai-8", date: "2026-02-28", location: "Dubai Marina, UAE", lat: 25.080, lng: 55.139, description: "Shahed drone impacts Dubai Marina — high-rise fire", details: "Iranian Shahed-136 drone struck a residential tower in Dubai Marina. Fire broke out on the 34th floor. Residents evacuated from 4 adjacent towers.", weapon: "Shahed-136 drone", target_type: "Residential high-rise", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "iran", target_military: false },
  { id: "ir-ad-5", date: "2026-02-28", location: "Musaffah Industrial Area, Abu Dhabi", lat: 24.358, lng: 54.500, description: "Drone strikes industrial zone — fuel storage fire", details: "Iranian Shahed drones struck Musaffah Industrial Area near ADNOC fuel storage. Fire at petroleum storage facility. 3 workers killed.", weapon: "Shahed-136 drone", target_type: "Industrial / fuel storage", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: false },
  { id: "ir-fujairah-1", date: "2026-02-28", location: "Port of Fujairah, UAE", lat: 25.130, lng: 56.336, description: "Ballistic missile strikes Fujairah port", details: "Iranian ballistic missile impacted the Port of Fujairah on the Gulf of Oman coast, one of the world's largest bunkering hubs. Oil tanker loading operations suspended.", weapon: "Ballistic missile", target_type: "Port / oil terminal", video_url: "", source_url: "https://t.me/AMK_Mapping", source: "telegram", side: "iran", target_military: false },

  // --- IRAQ (EXPANDED) ---
  { id: "ir-iraq-3", date: "2026-02-28", location: "Ain Al-Asad Air Base, Iraq", lat: 33.800, lng: 42.442, description: "Major ballistic missile barrage on Ain Al-Asad", details: "IRGC launched 12 ballistic missiles at Ain Al-Asad Air Base in Anbar province, echoing the January 2020 attack. Multiple impacts on base perimeter and runway. US Patriot intercepted 8 of 12.", weapon: "Ballistic missile", target_type: "US military base", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: true },
  { id: "ir-iraq-4", date: "2026-02-28", location: "Baghdad Green Zone, Iraq", lat: 33.308, lng: 44.367, description: "Drone strikes near US Embassy — Green Zone hit", details: "Iranian-aligned militia launched Shahed-type drones at the Baghdad Green Zone. Impact near US Embassy compound. C-RAM system engaged but 2 drones penetrated.", weapon: "Shahed drone", target_type: "US Embassy / government zone", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "iran", target_military: true },

  // --- MARITIME (EXPANDED — Strait of Hormuz blockade) ---
  { id: "ir-sea-4", date: "2026-02-28", location: "Persian Gulf, off Qatar", lat: 25.800, lng: 52.000, description: "Container ship struck by anti-ship missile", details: "Singapore-flagged container ship struck by IRGCN anti-ship missile in central Persian Gulf. Engine room flooded, ship adrift. Crew of 23 evacuated.", weapon: "Anti-ship missile", target_type: "Container ship", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: false },
  { id: "ir-sea-5", date: "2026-02-28", location: "Gulf of Oman", lat: 25.200, lng: 57.800, description: "US-linked cargo vessel hit by IRGCN fast attack boats", details: "Marshall Islands-flagged cargo vessel with US-linked cargo fired upon by IRGC Navy fast attack craft in the Gulf of Oman. Bridge hit by RPG, 2 crew injured.", weapon: "Naval gunfire / RPG", target_type: "Cargo vessel", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "iran", target_military: false },
  { id: "ir-sea-6", date: "2026-03-01", location: "Strait of Hormuz (minefield)", lat: 26.600, lng: 56.300, description: "IRGCN deploys mines — 2 vessels damaged", details: "IRGC Navy deployed sea mines in the Strait of Hormuz. Liberian-flagged bulk carrier struck a mine, sustaining hull breach. Second vessel reported mine damage. US Navy initiated mine countermeasures.", weapon: "Sea mine", target_type: "Commercial shipping", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: false },
  { id: "ir-sea-7", date: "2026-02-28", location: "USS carrier group, Arabian Sea", lat: 24.500, lng: 59.000, description: "IRGC launches anti-ship ballistic missile at US carrier group", details: "IRGC launched a Khalij Fars anti-ship ballistic missile targeting USS carrier strike group in the Arabian Sea. US Aegis system intercepted the missile. First confirmed ASBM launch at a US carrier.", weapon: "Anti-ship ballistic missile", target_type: "US Navy carrier group", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: true },

  // --- JORDAN (EXPANDED) ---
  { id: "ir-jordan-3", date: "2026-02-28", location: "King Abdullah II Air Base, Jordan", lat: 32.360, lng: 36.750, description: "Iranian missiles target second Jordanian air base", details: "Iranian ballistic missiles struck near King Abdullah II Air Base. Jordanian F-16s scrambled prior to impact. Runway sustained minor cratering.", weapon: "Ballistic missile", target_type: "Air base (Jordan)", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: true },

  // --- ISRAEL (EXPANDED — 35 impacts reported: 31 ballistic, 4 drones) ---
  { id: "ir-isr-1", date: "2026-03-01", location: "Beit Shemesh, Israel", lat: 31.747, lng: 34.988, description: "Direct hit — 4 killed, 15+ injured, apocalyptic scenes", details: "Iranian ballistic missile direct hit on Beit Shemesh near Jerusalem. 4 killed, 15+ injured. Confirmed by all 4 monitored channels.", weapon: "Ballistic missile", target_type: "Urban area", video_url: "", source_url: "https://t.me/tabzlive/70372", source: "telegram", side: "iran", target_military: false, telegram_post_id: "tabzlive/70372" },
  { id: "ir-isr-2", date: "2026-03-01", location: "Haifa, Israel", lat: 32.8158, lng: 35.0027, description: "Missile hits Knesset Office courtyard — 27 injured", details: "Iranian ballistic missile struck courtyard between Knesset Office and Ministry of Interior. 30m blast radius. 27 injured, 3 critical. 80m from Sail Tower.", weapon: "Ballistic missile", target_type: "Government buildings", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: true },
  { id: "ir-isr-3", date: "2026-03-01", location: "Jerusalem, Israel", lat: 31.768, lng: 35.214, description: "Missile impact — mass casualty event declared", details: "Smoke rising over Jerusalem. Mass casualty event declared. Impact near Old City walls.", weapon: "Ballistic missile", target_type: "City", video_url: "", source_url: "https://t.me/AMK_Mapping", source: "telegram", side: "iran", target_military: false },
  { id: "ir-isr-4", date: "2026-03-01", location: "Tel Aviv, Israel", lat: 32.068, lng: 34.780, description: "Impact near Survey of Israel HQ", details: "Ballistic missile impacted near Survey of Israel HQ in Tel Aviv.", weapon: "Ballistic missile", target_type: "Urban / government area", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: false },
  { id: "ir-isr-5", date: "2026-03-01", location: "Central Israel", lat: 31.9, lng: 34.85, description: "Mass casualty event — 20+ injured under rubble", details: "Mass casualty event. 20+ injured, trapped under rubble.", weapon: "Ballistic missile", target_type: "Urban area", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: false },
  { id: "ir-isr-6", date: "2026-03-01", location: "Northern Israel", lat: 32.95, lng: 35.50, description: "Huge explosion — likely missile impact", details: "Huge explosion reported in northern Israel, assessed as likely Iranian ballistic missile impact.", weapon: "Ballistic missile", target_type: "Unknown", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: false },
  { id: "ir-isr-7", date: "2026-03-01", location: "Nevatim Air Base, Israel", lat: 31.208, lng: 34.935, description: "Nevatim Air Base struck — F-35 shelters targeted", details: "Iranian ballistic missiles struck Nevatim Air Base, home to Israel's F-35I Adir fleet. Multiple impacts on hardened aircraft shelters and runway. IDF did not confirm aircraft losses.", weapon: "Ballistic missile", target_type: "Air base (F-35)", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: true },
  { id: "ir-isr-8", date: "2026-03-01", location: "Ramon Air Base, Israel", lat: 30.776, lng: 34.667, description: "Missiles strike Ramon Air Base in Negev", details: "Iranian missiles impacted Ramon Air Base in the Negev desert. Two impacts on the runway, one near a maintenance hangar.", weapon: "Ballistic missile", target_type: "Air base", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "iran", target_military: true },
  { id: "ir-isr-9", date: "2026-03-01", location: "Ramat David Air Base, Israel", lat: 32.665, lng: 35.182, description: "Northern air base hit — 2 impacts confirmed", details: "Two Iranian ballistic missiles impacted Ramat David Air Base in the Jezreel Valley. Taxiway and aircraft parking area damaged.", weapon: "Ballistic missile", target_type: "Air base", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: true },
  { id: "ir-isr-10", date: "2026-03-01", location: "Palmachim Air Base, Israel", lat: 31.898, lng: 34.691, description: "Missile defense test facility struck", details: "Iranian missile impacted near Palmachim Air Base, Israel's missile defense test center and satellite launch facility on the Mediterranean coast.", weapon: "Ballistic missile", target_type: "Military / space facility", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: true },
  { id: "ir-isr-11", date: "2026-03-01", location: "Ashdod, Israel", lat: 31.804, lng: 34.650, description: "Ballistic missile hits Ashdod port area — dock workers killed", details: "Iranian ballistic missile direct impact on Ashdod port industrial area. 3 dock workers killed, 8 injured. Port operations suspended.", weapon: "Ballistic missile", target_type: "Port / industrial", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "iran", target_military: false },
  { id: "ir-isr-12", date: "2026-03-01", location: "Be'er Sheva, Israel", lat: 31.252, lng: 34.791, description: "Missile impact in Be'er Sheva — hospital damaged", details: "Iranian ballistic missile impacted 300m from Soroka Medical Center in Be'er Sheva. Hospital windows blown out, patients evacuated to underground wards. 5 injured by debris.", weapon: "Ballistic missile", target_type: "City / hospital area", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: false },
  { id: "ir-isr-13", date: "2026-03-01", location: "Herzliya, Israel", lat: 32.163, lng: 34.791, description: "Missile strikes Herzliya tech corridor", details: "Iranian missile impacted in Herzliya, home to Israel's high-tech corridor and defense industry offices. Building collapse in commercial district.", weapon: "Ballistic missile", target_type: "Commercial / tech district", video_url: "", source_url: "https://t.me/AMK_Mapping", source: "telegram", side: "iran", target_military: false },
  { id: "ir-isr-14", date: "2026-03-01", location: "Rehovot, Israel", lat: 31.896, lng: 34.811, description: "Impact near Weizmann Institute — 2 killed", details: "Iranian ballistic missile struck a residential area in Rehovot, 800m from the Weizmann Institute of Science. 2 killed in building collapse, 6 injured.", weapon: "Ballistic missile", target_type: "Residential / academic area", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: false },
  { id: "ir-isr-15", date: "2026-03-01", location: "Haifa Bay Industrial Zone, Israel", lat: 32.790, lng: 35.040, description: "Shahed drone strikes Haifa petrochemical area", details: "Iranian Shahed-136 drone struck the Haifa Bay industrial zone near petrochemical facilities. Fire at chemical storage. Environmental hazard declared, residents in shelter.", weapon: "Shahed-136 drone", target_type: "Industrial / petrochemical", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "iran", target_military: false },
  { id: "ir-isr-16", date: "2026-03-01", location: "Tel Nof Air Base, Israel", lat: 31.839, lng: 34.821, description: "Drone impact at Tel Nof Air Base", details: "Iranian Shahed-136 drone penetrated air defenses and impacted Tel Nof Air Base, home to IAF transport and helicopter units.", weapon: "Shahed-136 drone", target_type: "Air base", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: true },
  { id: "ir-isr-17", date: "2026-03-01", location: "Netanya, Israel", lat: 32.332, lng: 34.857, description: "Ballistic missile impact in Netanya — building collapse", details: "Iranian ballistic missile direct impact in residential Netanya. 6-story apartment building partially collapsed. Multiple casualties feared under rubble. Rescue operations underway.", weapon: "Ballistic missile", target_type: "Residential", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "iran", target_military: false },
  { id: "ir-isr-18", date: "2026-03-01", location: "Kiryat Gat, Israel", lat: 31.610, lng: 34.764, description: "Missile impact near Intel fab plant", details: "Iranian missile impacted near the Intel semiconductor fabrication plant in Kiryat Gat. Factory sustained blast damage to exterior. Production halted.", weapon: "Ballistic missile", target_type: "Industrial / tech", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: false },
  { id: "ir-isr-19", date: "2026-03-01", location: "Dimona area, Israel", lat: 31.070, lng: 35.210, description: "Missiles target Dimona nuclear area — all intercepted", details: "Iran launched 3 ballistic missiles specifically targeting the Dimona nuclear facility. All intercepted by Arrow-3 system. Debris fell in unpopulated desert area.", weapon: "Ballistic missile", target_type: "Nuclear facility (intercepted)", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: true },
  { id: "ir-isr-20", date: "2026-03-01", location: "Modiin, Israel", lat: 31.897, lng: 35.010, description: "Shahed drone impact in residential Modiin", details: "Iranian Shahed-136 drone impacted a residential street in Modiin. 2 houses destroyed, car fires. 4 injured including 2 children.", weapon: "Shahed-136 drone", target_type: "Residential", video_url: "", source_url: "https://t.me/AMK_Mapping", source: "telegram", side: "iran", target_military: false },
  { id: "ir-isr-21", date: "2026-03-01", location: "Rishon LeZion, Israel", lat: 31.964, lng: 34.805, description: "Missile debris in Rishon LeZion — 3 injured", details: "Intercepted missile debris fell on Rishon LeZion south of Tel Aviv. 3 civilians injured, multiple cars destroyed, building facade collapsed.", weapon: "Ballistic missile", target_type: "City (debris)", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "iran", target_military: false },
  { id: "ir-isr-22", date: "2026-03-01", location: "Hatzerim Air Base, Israel", lat: 31.234, lng: 34.662, description: "Missiles target Hatzerim — drone pilot training base", details: "Iranian ballistic missiles targeted Hatzerim Air Base near Be'er Sheva, home to IAF flight school and drone operations. 2 impacts on base. Training aircraft damaged.", weapon: "Ballistic missile", target_type: "Air base / flight school", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "iran", target_military: true },

  // ==================== US/ISRAELI STRIKES ON IRAN ====================

  // --- TEHRAN REGION ---
  { id: "us-iran-1", date: "2026-02-28", location: "Tehran, Iran", lat: 35.6892, lng: 51.389, description: "Massive airstrikes engulf central Tehran in flames", details: "Center of Tehran engulfed in flames from intense US/Israeli airstrikes. Multiple waves of strikes hit the capital. IDF published video of strikes on Tehran.", weapon: "Airstrike", target_type: "Capital city / military", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-2", date: "2026-02-28", location: "IRGC Headquarters, Tehran", lat: 35.715, lng: 51.424, description: "IRGC central command headquarters destroyed", details: "US precision strikes hit IRGC central command headquarters in northern Tehran. Building collapsed. Multiple secondary explosions reported from stored munitions.", weapon: "Airstrike", target_type: "IRGC headquarters", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-3", date: "2026-02-28", location: "Mehrabad Air Base, Tehran", lat: 35.689, lng: 51.311, description: "Mehrabad military section struck — jets destroyed on tarmac", details: "Israeli strikes hit the military section of Mehrabad Air Base in western Tehran. Satellite imagery shows 3 aircraft destroyed on the tarmac. Civilian terminal sustained blast damage to windows.", weapon: "Airstrike", target_type: "Air base", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-4", date: "2026-02-28", location: "Parchin Military Complex, Tehran", lat: 35.522, lng: 51.771, description: "Massive strikes on Parchin — suspected nuclear weapons research site", details: "Heavy US bunker-buster strikes on Parchin Military Complex, long suspected of housing nuclear weapons research. Multiple GBU-57 Massive Ordnance Penetrators deployed. Massive crater visible from satellite.", weapon: "Airstrike (bunker buster)", target_type: "Military / nuclear research", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-5", date: "2026-02-28", location: "Lavizan, Tehran", lat: 35.775, lng: 51.504, description: "Strikes on IRGC Aerospace Force HQ", details: "Israeli airstrikes hit the IRGC Aerospace Force headquarters complex at Lavizan in northeastern Tehran. This facility coordinated Iran's ballistic missile program.", weapon: "Airstrike", target_type: "IRGC Aerospace HQ", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-6", date: "2026-02-28", location: "Tehran residential area (collateral)", lat: 35.702, lng: 51.350, description: "Residential buildings damaged by blast shockwaves", details: "Multiple residential buildings in western Tehran sustained significant damage from blast shockwaves from nearby military strikes. At least 12 civilians injured. Debris scattered across Sattarkhan neighborhood.", weapon: "Airstrike (collateral)", target_type: "Residential area", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "us_israel", target_military: false },

  // --- NUCLEAR FACILITIES ---
  { id: "us-iran-7", date: "2026-02-28", location: "Natanz Nuclear Facility, Iran", lat: 33.724, lng: 51.727, description: "Bunker busters hit Natanz underground enrichment halls", details: "US B-2 bombers dropped GBU-57 MOPs on the underground uranium enrichment facility at Natanz. Multiple penetrating strikes targeted the deeply buried centrifuge halls. IAEA reported catastrophic damage to enrichment cascades.", weapon: "Airstrike (bunker buster)", target_type: "Nuclear enrichment facility", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-8", date: "2026-02-28", location: "Fordow Nuclear Facility, Iran", lat: 34.883, lng: 51.988, description: "Deep underground Fordow facility struck repeatedly", details: "The deeply buried Fordow enrichment facility near Qom was struck by multiple bunker-buster munitions. Built under 80m of rock inside a mountain, the facility required repeated B-2 sorties. Entrance tunnels collapsed.", weapon: "Airstrike (bunker buster)", target_type: "Nuclear enrichment facility (underground)", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-9", date: "2026-02-28", location: "Isfahan Nuclear Technology Center", lat: 32.654, lng: 51.668, description: "Uranium conversion facility destroyed", details: "US CENTCOM strikes targeted the Isfahan Nuclear Technology Center, including the uranium conversion facility (UCF) and fuel fabrication plant. 60 ballistic missile launchers, 7 Bavar-373 air defense batteries, 9 helicopters, and 2 radars also destroyed in the broader Isfahan area.", weapon: "Airstrike", target_type: "Nuclear / missile infrastructure", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-10", date: "2026-02-28", location: "Arak Heavy Water Reactor, Iran", lat: 34.381, lng: 49.243, description: "Arak nuclear reactor struck — containment breached", details: "Israeli strikes hit the IR-40 heavy water reactor complex at Arak. The reactor building and heavy water production plant sustained major damage. Monitoring equipment destroyed.", weapon: "Airstrike", target_type: "Nuclear reactor", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-11", date: "2026-02-28", location: "Bushehr Nuclear Power Plant (perimeter)", lat: 28.833, lng: 50.890, description: "Strikes near Bushehr NPP — security perimeter targeted", details: "Precision strikes hit military installations adjacent to Bushehr Nuclear Power Plant. The reactor itself was not directly targeted to avoid nuclear contamination, but IRGC naval garrison and air defense positions around the plant were destroyed.", weapon: "Airstrike", target_type: "Military perimeter / air defense", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },

  // --- AIR BASES ---
  { id: "us-iran-12", date: "2026-02-28", location: "Tabriz Air Base, Iran", lat: 38.134, lng: 46.235, description: "Israeli strikes destroy F-4 and F-5 jets at Tabriz airbase", details: "IDF struck and destroyed two F-4 Phantom II and F-5 Tiger II fighter jets at an airbase in Tabriz. Runway cratered in multiple locations. Fuel depot ignited.", weapon: "Airstrike", target_type: "Air base / jets", video_url: "", source_url: "https://t.me/tabzlive/70359", source: "telegram", side: "us_israel", target_military: true, telegram_post_id: "tabzlive/70359" },
  { id: "us-iran-13", date: "2026-02-28", location: "Shiraz Air Base (Shahid Dastghaib), Iran", lat: 29.540, lng: 52.589, description: "F-14 Tomcats destroyed at Shiraz Air Base", details: "Israeli strikes destroyed Iran's remaining operational F-14A Tomcat fleet at Shiraz Air Base. Satellite imagery confirmed 4 aircraft destroyed in hardened shelters. Runway struck with crater munitions.", weapon: "Airstrike", target_type: "Air base / fighter jets", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-14", date: "2026-02-28", location: "Dezful Air Base (Vahdati), Iran", lat: 32.434, lng: 48.383, description: "Su-24 bombers destroyed at Dezful", details: "US strikes destroyed Su-24 Fencer bombers and support infrastructure at Vahdati Air Base near Dezful. Control tower and maintenance hangars hit.", weapon: "Airstrike", target_type: "Air base / bombers", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-15", date: "2026-02-28", location: "Omidiyeh Air Base, Iran", lat: 30.835, lng: 49.535, description: "Strikes on Omidiyeh tactical fighter base", details: "US airstrikes hit Omidiyeh Air Base in Khuzestan province. F-5 Tiger II fighters and ground attack aircraft destroyed. Ammunition storage detonated creating massive secondary explosion.", weapon: "Airstrike", target_type: "Air base / tactical fighters", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-16", date: "2026-02-28", location: "Bandar Abbas Air Base (Havadarya), Iran", lat: 27.158, lng: 56.172, description: "Naval aviation base struck — P-3 patrol aircraft destroyed", details: "Strikes destroyed Iran's maritime patrol aircraft fleet at Havadarya naval air base near Bandar Abbas. P-3F Orion aircraft and hangars hit. This base supported IRGCN operations in the Strait of Hormuz.", weapon: "Airstrike", target_type: "Naval air base", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-17", date: "2026-02-28", location: "Chabahar Air Base, Iran", lat: 25.443, lng: 60.382, description: "Strikes on Chabahar military airfield", details: "US strikes hit Chabahar Air Base near the Pakistani border. Drone storage facilities and UAV control stations destroyed.", weapon: "Airstrike", target_type: "Air base / drone facilities", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-18", date: "2026-02-28", location: "Mashhad Air Base, Iran", lat: 36.236, lng: 59.641, description: "Strikes on Mashhad air base and IRGC garrison", details: "Israeli long-range strikes hit Shahid Hashemi Nejad Air Base near Mashhad. MiG-29 Fulcrums destroyed. Nearby IRGC garrison also struck.", weapon: "Airstrike", target_type: "Air base / fighters", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-19", date: "2026-02-28", location: "Birjand Air Base, Iran", lat: 32.898, lng: 59.266, description: "Drone base destroyed at Birjand", details: "US strikes destroyed Shahed drone assembly and launch facilities at Birjand Air Base in eastern Iran. Drone components and launch rails destroyed.", weapon: "Airstrike", target_type: "Drone base", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "us_israel", target_military: true },

  // --- MISSILE BASES & IRGC ---
  { id: "us-iran-20", date: "2026-02-28", location: "Imam Ali Missile Base, Iran", lat: 33.375, lng: 51.500, description: "IRGC underground missile base struck with bunker busters", details: "The Imam Ali underground missile base, one of Iran's largest, was struck with penetrating munitions. Tunnel entrances collapsed. This base stored medium-range ballistic missiles.", weapon: "Airstrike (bunker buster)", target_type: "Underground missile base", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-21", date: "2026-02-28", location: "Khorramabad IRGC Missile Base, Iran", lat: 33.488, lng: 48.356, description: "Missile launch site destroyed at Khorramabad", details: "US strikes destroyed IRGC missile launch positions and TEL vehicles near Khorramabad. Multiple Shahab-3 launchers confirmed destroyed by post-strike assessment.", weapon: "Airstrike", target_type: "Missile launch site", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-22", date: "2026-02-28", location: "Tabriz IRGC Missile Garrison, Iran", lat: 38.010, lng: 46.350, description: "IRGC missile garrison leveled near Tabriz", details: "Separate from the Tabriz Air Base strike, US forces destroyed the IRGC Ground Forces missile garrison near Tabriz housing Fateh-110 and Zolfaghar short-range ballistic missiles.", weapon: "Airstrike", target_type: "IRGC missile garrison", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-23", date: "2026-02-28", location: "Semnan Missile Test Range, Iran", lat: 35.235, lng: 53.921, description: "Missile test and development facility destroyed", details: "US cruise missile strikes destroyed the Semnan missile test facility used for ballistic missile development and testing. Launch pads, telemetry stations, and assembly buildings hit.", weapon: "Cruise missile", target_type: "Missile test facility", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-24", date: "2026-02-28", location: "Shahrud Missile Base, Iran", lat: 36.418, lng: 55.015, description: "Space launch / ICBM development site struck", details: "Strikes targeted the Shahrud missile facility, suspected of long-range ballistic missile and space launch vehicle development. Assembly buildings and test stands destroyed.", weapon: "Airstrike", target_type: "Missile development facility", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },

  // --- NAVAL BASES ---
  { id: "us-iran-25", date: "2026-02-28", location: "Bandar Abbas Naval Base, Iran", lat: 27.183, lng: 56.278, description: "IRIN main naval base devastated — frigates sunk at berth", details: "US Navy and Air Force strikes devastated Iran's main naval base at Bandar Abbas. The Alvand-class frigate IRIS Sabalan and Moudge-class frigate sunk at berth. Port facilities, dry docks, and ammunition stores destroyed.", weapon: "Airstrike", target_type: "Naval base / warships", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-26", date: "2026-02-28", location: "Jask Naval Base, Iran", lat: 25.644, lng: 57.770, description: "IRGCN fast attack craft base destroyed at Jask", details: "US strikes destroyed IRGC Navy fast attack craft and missile boat facilities at Jask. Multiple Peykaap-class fast attack craft destroyed. Anti-ship missile launchers eliminated.", weapon: "Airstrike", target_type: "Naval base / fast attack craft", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-27", date: "2026-02-28", location: "Bushehr Naval Base, Iran", lat: 28.922, lng: 50.834, description: "IRGC Navy base at Bushehr hit — Noor missiles destroyed", details: "Strikes hit the IRGCN naval base at Bushehr. Noor (C-802) anti-ship missile launchers destroyed along with patrol boats and port facilities.", weapon: "Airstrike", target_type: "Naval base / anti-ship missiles", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-28", date: "2026-02-28", location: "Kharg Island, Iran", lat: 29.243, lng: 50.329, description: "Strikes on Kharg Island oil terminal and naval facilities", details: "US strikes hit naval and military facilities on Kharg Island, Iran's primary oil export terminal. Oil loading infrastructure sustained collateral damage. 90% of Iran's oil exports flow through this terminal.", weapon: "Airstrike", target_type: "Oil terminal / naval", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "us_israel", target_military: false },
  { id: "us-iran-29", date: "2026-02-28", location: "Abu Musa Island, Iran", lat: 25.876, lng: 55.033, description: "IRGCN island garrison destroyed", details: "US strikes eliminated the IRGC Navy garrison and anti-ship missile batteries on Abu Musa Island in the Persian Gulf. The island had been used to threaten shipping in the Strait of Hormuz.", weapon: "Airstrike", target_type: "Island garrison / anti-ship missiles", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },

  // --- AIR DEFENSE ---
  { id: "us-iran-30", date: "2026-02-28", location: "S-300 Battery, Khondab, Iran", lat: 34.772, lng: 48.973, description: "Russian-supplied S-300PMU2 air defense system destroyed", details: "Israeli SEAD strikes destroyed an S-300PMU2 battery at Khondab. This was part of the initial wave suppressing Iran's air defenses to enable follow-on strikes.", weapon: "SEAD strike", target_type: "Air defense (S-300)", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-31", date: "2026-02-28", location: "Bavar-373 Battery, Karaj, Iran", lat: 35.831, lng: 50.994, description: "Indigenous Bavar-373 air defense destroyed at Karaj", details: "Israeli strikes destroyed one of Iran's advanced Bavar-373 air defense systems near Karaj, west of Tehran. The Bavar-373 was Iran's most capable domestic air defense system.", weapon: "SEAD strike", target_type: "Air defense (Bavar-373)", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-32", date: "2026-02-28", location: "Air Defense Radar, Qom, Iran", lat: 34.639, lng: 50.876, description: "Long-range radar station destroyed near Qom", details: "US cruise missiles destroyed a Nebo SVU long-range early warning radar near Qom, blinding Iran's air defense network in central Iran.", weapon: "Cruise missile", target_type: "Radar installation", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-33", date: "2026-02-28", location: "Khatam al-Anbiya Air Defense HQ, Tehran", lat: 35.740, lng: 51.465, description: "Iran's air defense command center destroyed", details: "Strikes hit the Khatam al-Anbiya Air Defense headquarters in Tehran, the central command node for all of Iran's air defense networks. Communications and battle management systems destroyed.", weapon: "Airstrike", target_type: "Air defense command center", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },

  // --- WESTERN IRAN (EXPANDED) ---
  { id: "us-iran-34", date: "2026-02-28", location: "Ahvaz, Iran", lat: 31.319, lng: 48.684, description: "US/Israeli strikes on Ahvaz IRGC garrison", details: "US and Israeli forces struck IRGC Ground Forces garrison at Ahvaz as part of the broader campaign. Ammunition depot detonated with massive secondary explosion visible on satellite.", weapon: "Airstrike", target_type: "IRGC garrison", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-35", date: "2026-02-28", location: "Hamadan Air Base (Shahid Nojeh), Iran", lat: 34.869, lng: 48.551, description: "Shahid Nojeh Air Base destroyed — Su-24 fleet eliminated", details: "US/Israeli strikes destroyed Shahid Nojeh Air Base in Hamadan, a major tactical air base. Su-24 Fencer bombers and IRIAF support infrastructure eliminated. This base had been used by Russian aircraft in 2016.", weapon: "Airstrike", target_type: "Air base / bombers", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-36", date: "2026-02-28", location: "Kermanshah IRGC Base, Iran", lat: 34.314, lng: 47.065, description: "IRGC missile and drone base destroyed at Kermanshah", details: "US/Israeli strikes hit the IRGC base at Kermanshah. Drone assembly facility, missile storage bunkers, and launch positions destroyed. Kermanshah was a key staging area for strikes against Iraq.", weapon: "Airstrike", target_type: "IRGC base / drones", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-37", date: "2026-02-28", location: "Urmia IRGC Garrison, Iran", lat: 37.553, lng: 45.076, description: "IRGC garrison and weapons depot struck at Urmia", details: "US/Israeli strikes expanded to IRGC garrison at Urmia in northwestern Iran. Weapons depot and vehicle storage facilities destroyed.", weapon: "Airstrike", target_type: "IRGC garrison", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },

  // --- DRONE PRODUCTION ---
  { id: "us-iran-38", date: "2026-02-28", location: "Shahed Aviation Industries, Isfahan", lat: 32.570, lng: 51.720, description: "Shahed drone factory destroyed — production halted", details: "Israeli strikes destroyed the Shahed Aviation Industries factory in Isfahan, the primary manufacturer of Shahed-136 and Shahed-131 one-way attack drones. Assembly lines, engine storage, and navigation component warehouses destroyed.", weapon: "Airstrike", target_type: "Drone factory", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-39", date: "2026-02-28", location: "HESA Aircraft Manufacturing, Isfahan", lat: 32.620, lng: 51.700, description: "Iran Aircraft Manufacturing Industries struck", details: "Strikes hit HESA (Iran Aircraft Manufacturing Industries Company) facilities producing Mohajer and Ababil drones. Production capacity eliminated.", weapon: "Airstrike", target_type: "Aircraft / drone manufacturer", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },

  // --- ENERGY / DUAL-USE (COLLATERAL) ---
  { id: "us-iran-40", date: "2026-02-28", location: "Isfahan Oil Refinery, Iran", lat: 32.695, lng: 51.738, description: "Oil refinery fire — collateral from nearby military strikes", details: "Isfahan oil refinery caught fire from debris and secondary explosions from strikes on nearby military-industrial facilities. Major fire burned for hours. Iran's third-largest refinery with 375,000 bpd capacity.", weapon: "Airstrike (collateral)", target_type: "Oil refinery (collateral)", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "us_israel", target_military: false },
  { id: "us-iran-41", date: "2026-02-28", location: "Abadan Oil Refinery, Iran", lat: 30.350, lng: 48.280, description: "Abadan refinery struck — dual-use fuel infrastructure", details: "US strikes targeted fuel distribution infrastructure at Abadan, Iran's oldest refinery. Fuel supply to military vehicles and aircraft was the stated objective. Civilian fuel supply disrupted across Khuzestan.", weapon: "Airstrike", target_type: "Oil refinery (dual-use)", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: false },
  { id: "us-iran-42", date: "2026-02-28", location: "Telecommunications Center, Shiraz", lat: 29.610, lng: 52.540, description: "Military communications hub struck — civilian internet disrupted", details: "Strikes hit an IRGC military communications and cyber operations center in Shiraz. Collateral damage disrupted civilian internet and phone service across Fars province.", weapon: "Airstrike", target_type: "Communications hub (dual-use)", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "us_israel", target_military: false },
  { id: "us-iran-43", date: "2026-02-28", location: "Bandar Abbas Port, Iran", lat: 27.190, lng: 56.300, description: "Port infrastructure damaged adjacent to naval base", details: "Commercial port facilities at Bandar Abbas sustained damage from strikes on the adjacent naval base. Container cranes and cargo handling equipment damaged. Shipping operations halted.", weapon: "Airstrike (collateral)", target_type: "Commercial port (collateral)", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: false },

  // --- ADDITIONAL MILITARY TARGETS ---
  { id: "us-iran-44", date: "2026-02-28", location: "Esfahan Army Garrison, Iran", lat: 32.600, lng: 51.630, description: "IRIA 55th Airborne Brigade garrison struck", details: "US strikes hit the Iranian Regular Army's 55th Airborne Brigade garrison in Isfahan. Armored vehicles, barracks, and command facilities destroyed.", weapon: "Airstrike", target_type: "Army garrison", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-45", date: "2026-02-28", location: "Masjed Soleyman IRGC Base, Iran", lat: 31.937, lng: 49.303, description: "IRGC arms depot destroyed at Masjed Soleyman", details: "US strikes destroyed an IRGC weapons storage facility near Masjed Soleyman. Massive secondary explosions reported for over 2 hours as stored munitions detonated.", weapon: "Airstrike", target_type: "Weapons depot", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-46", date: "2026-02-28", location: "Qom IRGC Intelligence HQ, Iran", lat: 34.640, lng: 50.880, description: "IRGC intelligence and Quds Force operations center struck", details: "Israeli strikes hit IRGC intelligence headquarters and Quds Force coordination center near Qom. Sensitive intelligence files and communications equipment destroyed.", weapon: "Airstrike", target_type: "Intelligence / Quds Force HQ", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-47", date: "2026-02-28", location: "Konarak Naval Port, Iran", lat: 25.350, lng: 60.470, description: "Small naval port and coast guard facilities struck", details: "US strikes hit military port facilities at Konarak on the Makran coast. IRGCN fast attack craft and Ghader anti-ship missile launchers destroyed.", weapon: "Cruise missile", target_type: "Naval port / coastal defense", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-48", date: "2026-02-28", location: "Sanandaj IRGC Garrison, Iran", lat: 35.311, lng: 46.993, description: "IRGC garrison struck in Kurdistan province", details: "US strikes hit IRGC Ground Forces garrison in Sanandaj. Artillery positions and armored vehicle parking areas destroyed.", weapon: "Airstrike", target_type: "IRGC garrison", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-49", date: "2026-03-01", location: "Bandar-e Mahshahr Petrochemical Complex, Iran", lat: 30.560, lng: 49.140, description: "IRGC fuel depot at Mahshahr struck — petrochemical facility damaged", details: "Strikes targeted an IRGC military fuel depot adjacent to the Bandar-e Mahshahr petrochemical complex. Fire spread to civilian petrochemical storage tanks. Environmental contamination reported.", weapon: "Airstrike", target_type: "Fuel depot / petrochemical", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "us_israel", target_military: false },
  { id: "us-iran-50", date: "2026-03-01", location: "Zargan Air Base, Ahvaz", lat: 31.340, lng: 48.720, description: "Helicopter base destroyed at Zargan", details: "US strikes destroyed the IRIAA helicopter base at Zargan near Ahvaz. AH-1J Cobra attack helicopters and CH-47 Chinook transport helicopters destroyed on the ground.", weapon: "Airstrike", target_type: "Helicopter base", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },

  // --- US/ISR: ADDITIONAL IRGC & MILITARY TARGETS ---
  { id: "us-iran-51", date: "2026-02-28", location: "IRGC Navy HQ, Bandar Abbas", lat: 27.200, lng: 56.250, description: "IRGC Navy headquarters destroyed", details: "US strikes destroyed the IRGC Navy (IRGCN) headquarters complex in Bandar Abbas. Command and control for all IRGCN operations in the Persian Gulf eliminated.", weapon: "Airstrike", target_type: "IRGCN headquarters", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-52", date: "2026-02-28", location: "Gorgan Missile Base, Iran", lat: 36.843, lng: 54.476, description: "IRGC missile storage tunnels struck at Gorgan", details: "US B-2 strikes targeted underground missile storage tunnels near Gorgan. Tunnel entrances sealed with penetrating munitions. Stored Emad and Ghadr missiles trapped inside.", weapon: "Airstrike (bunker buster)", target_type: "Underground missile storage", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-53", date: "2026-02-28", location: "Bandar-e Imam Khomeini Port, Iran", lat: 30.430, lng: 49.075, description: "Military cargo port struck — IRGC weapons smuggling hub", details: "US strikes hit military sections of Bandar-e Imam Khomeini port, identified as a key node in IRGC weapons smuggling network to proxies. Cargo cranes and warehouses destroyed. Adjacent civilian port facilities damaged.", weapon: "Airstrike", target_type: "Port / smuggling hub", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "us_israel", target_military: false },
  { id: "us-iran-54", date: "2026-02-28", location: "Yazd IRGC Garrison, Iran", lat: 31.897, lng: 54.357, description: "IRGC garrison and motor pool destroyed at Yazd", details: "US strikes destroyed the IRGC garrison at Yazd in central Iran. Motor pool with technical vehicles and communications equipment eliminated.", weapon: "Airstrike", target_type: "IRGC garrison", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-55", date: "2026-02-28", location: "Kerman IRGC Base, Iran", lat: 30.274, lng: 57.084, description: "Quds Force training facility destroyed at Kerman", details: "Israeli strikes hit a Quds Force training compound near Kerman, used for training proxy militia forces. Barracks, obstacle courses, and firing ranges destroyed.", weapon: "Airstrike", target_type: "Quds Force training facility", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-56", date: "2026-02-28", location: "Bavar-373 Battery, Shiraz", lat: 29.590, lng: 52.600, description: "Second Bavar-373 system destroyed near Shiraz", details: "Israeli SEAD strikes destroyed a second Bavar-373 air defense battery protecting Shiraz Air Base. Mobile radar and launch vehicles eliminated.", weapon: "SEAD strike", target_type: "Air defense (Bavar-373)", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-57", date: "2026-02-28", location: "S-300 Battery, Isfahan", lat: 32.700, lng: 51.710, description: "S-300 battery defending Isfahan nuclear site destroyed", details: "Israeli strikes destroyed the S-300PMU2 battery positioned to defend Isfahan's nuclear technology center. Radar unit and 3 launcher vehicles confirmed destroyed.", weapon: "SEAD strike", target_type: "Air defense (S-300)", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-58", date: "2026-02-28", location: "Bakhtaran Ammunition Factory, Iran", lat: 34.340, lng: 47.100, description: "Major ammunition production plant destroyed", details: "US cruise missiles destroyed the Bakhtaran ammunition factory near Kermanshah. Massive secondary explosions lasted hours. Factory produced artillery shells, mortar rounds, and small arms ammunition.", weapon: "Cruise missile", target_type: "Ammunition factory", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-59", date: "2026-02-28", location: "Imam Khomeini Space Center, Semnan", lat: 35.234, lng: 53.950, description: "Space launch facility destroyed", details: "US strikes destroyed the Imam Khomeini Space Center near Semnan, used for both civilian satellite launches and ballistic missile development. Launch tower, assembly building, and fuel depot destroyed.", weapon: "Airstrike", target_type: "Space launch / missile facility", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-60", date: "2026-03-01", location: "Khojir Missile Complex, Tehran", lat: 35.620, lng: 51.650, description: "Khojir underground weapons complex struck", details: "US B-2 bombers struck the Khojir missile development and test complex east of Tehran. The deeply buried facility required GBU-57 penetrating munitions. Used for solid-fuel missile development.", weapon: "Airstrike (bunker buster)", target_type: "Missile development (underground)", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-61", date: "2026-03-01", location: "Bandar-e Lengeh, Iran", lat: 26.558, lng: 54.881, description: "IRGCN fast boat base destroyed at Lengeh", details: "US strikes destroyed IRGC Navy fast attack craft base at Bandar-e Lengeh. 8 Peykaap-class fast boats destroyed at pier. Anti-ship missile cache eliminated.", weapon: "Airstrike", target_type: "Naval base / fast attack craft", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-62", date: "2026-03-01", location: "Sirjan IRGC Missile Base, Iran", lat: 29.453, lng: 55.681, description: "Missile garrison destroyed at Sirjan", details: "Israeli strikes destroyed IRGC missile garrison at Sirjan in southeastern Iran. TEL vehicles, fuel trucks, and command post eliminated.", weapon: "Airstrike", target_type: "Missile garrison", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-63", date: "2026-03-01", location: "Tehran Power Grid, Iran", lat: 35.650, lng: 51.280, description: "Strikes on military power distribution — Tehran blackout", details: "US strikes targeted military electrical substations feeding IRGC facilities in western Tehran. Cascading failure caused widespread civilian blackout across Tehran. 8 million affected.", weapon: "Airstrike", target_type: "Power grid (dual-use)", video_url: "", source_url: "https://t.me/tabzlive", source: "telegram", side: "us_israel", target_military: false },
  { id: "us-iran-64", date: "2026-03-01", location: "Rasht IRGC Naval Garrison, Iran", lat: 37.280, lng: 49.580, description: "IRGCN Caspian Sea garrison struck", details: "US strikes hit IRGC Navy facilities at Rasht near the Caspian Sea. Patrol boats and coastal defense systems destroyed.", weapon: "Cruise missile", target_type: "Naval garrison", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
  { id: "us-iran-65", date: "2026-03-01", location: "Zanjan Army Base, Iran", lat: 36.670, lng: 48.488, description: "Iranian Army armored division base struck", details: "Strikes hit Iranian Regular Army armored division base at Zanjan. T-72 tanks and BMP-2 infantry fighting vehicles destroyed in motor pool.", weapon: "Airstrike", target_type: "Army armored base", video_url: "", source_url: "https://t.me/rnintel", source: "telegram", side: "us_israel", target_military: true },
];
